name: kork
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  get: ^4.6.6
  intl_utils: ^2.8.9
  flutter_switch: ^0.3.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
#  http: ^1.3.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.4.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  blur: ^4.0.0
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.6
  flutter_spinkit: ^5.2.1
  pretty_qr_code: ^3.3.0
  file_saver: ^0.2.14
  media_scanner: ^2.2.0
  mobile_scanner: ^6.0.7
  get_storage: ^2.1.1
  screenshot: ^3.0.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
#  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
  adaptive_icon_background: "#252525"
  adaptive_icon_foreground: "assets/image/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/animation/
    - assets/image/
    - assets/image/svg/
    - assets/image/flags/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Light.ttf
          weight: 300
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/kantumruyPro/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Bold.ttf
          weight: 700

# flutter_native_splash:
#   color_dark: "#252525"  # Dark mode background
#   image_dark: assets/image/logo.png
  
#   color: "#F2F0F0"  # Light mode background
#   image: assets/image/light-logo.png

#   android_12:
#     image_dark: assets/image/logo.png
#     icon_background_color_dark: "#252525"
    
#     image: assets/image/light-logo.png
#     icon_background_color: "#F2F0F0"

flutter_native_splash:
  color: "#252525"
  image: assets/image/logo.png
  android_12:
    image: assets/image/logo.png
    icon_background_color: "#252525"