name: kork
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  get: ^4.6.6
  intl_utils: ^2.8.9
  flutter_switch: ^0.3.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  http: ^1.3.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.4.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  blur: ^4.0.0
  flutter_dotenv: ^5.2.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.10.0
  crypto: ^3.0.6
  email_otp: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/animation/
    - assets/image/
    - assets/image/svg/
    - assets/image/flags/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Light.ttf
          weight: 300
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/kantumruyPro/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Bold.ttf
          weight: 700