name: kork
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  get: ^4.6.6
  intl_utils: ^2.8.9
  flutter_switch: ^0.3.2
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
  http: ^1.3.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/image/
    - assets/image/svg/
    - assets/image/flags/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/KantumruyPro-VariableFont_wght.ttf
